default_language_version:
    python: python3.10
repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
        args: [ --unsafe ]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v9.6.0'
    hooks:
      - id: eslint
        files: \.[jt]s?$
        types: [ file ]
        additional_dependencies:
          - "@typescript-eslint/parser@^7.16.0"
          - "eslint@^8.57.0"
          - "eslint-config-prettier@^9.1.0"
          - "eslint-plugin-prettier@^5.1.3"